server:
  port: 9191
spring:
  datasource:
    url: jdbc:h2:mem:rentDB?createDatabaseIfNotExist=true
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

